client/urls.py
from django.urls import path, include
from .views import *
from .api import *

app_name = 'client'
urlpatterns = [
    path('', dashboard, name='dashboard'),

    path('profile/', profile, name='profile'),
    path('profile/password/', changepassword, name="password"),
    path('user/edit/<int:user_id>/', user_edit, name='user_edit'),

    path('setting/', user_settings, name="setting"),
    path('setting/edit/', user_settings, {'action': 'edit'}, name="setting_edit"),

    path('setting/<str:domain>/<path:path>', static_files, name="static_files"),

    path('login/', login, name='login'),
    path('verify/<str:user_cellphone>/', verify, name='verify'),
    path('logout/', Logout, name="logout"),

    path('status/', status, name="status"),

    path('users/', users, name="users"),
    path('users/<int:user_id>/active', activate_user, name='activeuser'),
    path('users/<int:user_id>/deactive', deactivate_user, name='deactiveuser'),
    path('plus_update_pass/', plus_update_pass, name="plus_update_pass"),

    path('admin/', admin, name="admin"),
    path('admin/<int:id>/', admin, name="admin"),
    path('admin/<int:id>/install/', admininstall, name="admininstall"),
    path('admin/<int:id>/install-sites/', install_sites, name="install-sites"),
    path('admin/<int:id>/remove/', adminremove, name="adminremove"),
    path('admin/<int:id>/siteuser/', check_or_createuser, name="siteuser"),
    path('admin/<str:id>/<str:user>/resetpassword/', resetpassword, name="resetpassword"),

    path('versions/', versions, name='versions'),
    path('versions/delete/<int:image_tag_id>/', version_delete, name='version_delete'),
    path('version/edit/<int:image_tag_id>/', version_edit, name='version_edit'),
    path('version/create/', version_create, name='version_create'),
    path('version/active/<int:id>/', edit_verion, {'action' : 'active'}, name="active_verion"),
    path('version/deactive/<int:id>/', edit_verion, {'action' : 'deactive'}, name="deactive_verion"),

    path('sites/', sites, name="sites"),

    # api
    path('api/select/theme/', api_select_theme, name='api_select_theme'),
    path('api/get/domain/config/<str:domain>/', api_get_domain_config, name='api_get_domain_donfig'),
    path('api/available/versions/', api_get_available_force_version, name='api_available_versions'),



    # should be moved
    path('timing/<int:user_id>/', timing, name='timing'),


    path('user/orders/', include('client.views.user_order.urls'), name='user_order'),
]

client/views/user_order/urls.py
from django.urls import path
from .views import *

app_name = 'user_order'

urlpatterns = [
    path('', user_orders, name='user_order'),
    path('user/order/active/', user_order_active, name='user_order_active'),
    path('user/order/inactive/', user_order_inactive, name='user_order_inactive')
]

order/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('', orders, name='orders'),
    path('order/create/', order_create, name='order_create'),
    path('order/edit/<int:order_id>/', order_edit, name='order_edit'),
    path('order/delete/<int:order_id>/', order_delete, name='order_delete'),
    path('order/detail/<int:order_id>/', order_detail, name='order_detail'),
    path('order/buy/<int:order_id>/', order_buy, name='order_buy'),
    path('order/buy/<int:order_id>/<int:setting_id>/', order_buy, name='order_buy'),

    path('static/files/<int:order_id>/', static_files, name='static_files')
]

vidoneplus/urls.py
from django.contrib import admin
from django.urls import path, include
from vidoneplus.views import *

urlpatterns = [
    path('', index, name="index"),
    path('validate_course/', validate_course),
    path('admin/', admin.site.urls),
    path('accounts/', include('client.urls')),
    path('course/', include('course.urls')),
    path('order/', include('order.urls')),
    path('page_not_found/', page_not_found, name='page_not_found'),
    path('page_not_found/<str:text>/', page_not_found, name='page_not_found'),
    path('page_not_found/<str:text>/<str:previous_url>/', page_not_found, name='page_not_found'),
]

client/views/user_order/views/imports.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from client.models import *
from order.models import *
from django.core.paginator import Paginator

client/views/user_order/views/user_order_active.py
from .imports import *


def user_order_active(request):
    context = {}
    user = User.objects.get(id=request.user.id)
    active_orders = Paginator(OrderItem.objects.filter(id__in=user.setting_set.all().values_list('orderitem__id', flat=True), status=True), 1)
    context['page'] = active_orders.get_page(1)
    if request.GET.get('page_number'):
        context['page'] = active_orders.get_page(request.GET.get('page_number'))
    context['page_url'] = 'client:user_order:user_order_active'
    return render(request, f'{__name__.replace(".", "/")}.html', context)

client/views/user_order/views/user_order_inactive.py
from .imports import *


def user_order_inactive(request):
    context = {}
    user = User.objects.get(id=request.user.id)
    inactive_orders = Paginator(OrderItem.objects.filter(id__in=user.setting_set.all().values_list('orderitem__id', flat=True), status=False), 1)
    context['page'] = inactive_orders.get_page(1)
    if request.GET.get('page_number'):
        context['page'] = inactive_orders.get_page(request.GET.get('page_number'))
    context['page_url'] = 'client:user_order:user_order_inactive'
    return render(request, f'{__name__.replace(".", "/")}.html', context)

client/views/user_order/views/user_orders.py
from .imports import *


def user_orders(request):
    context = {}
    return render(request, f'{__name__.replace(".", "/")}.html', context)

templates/client/views/user_order/views/user_order_active.html
{% extends 'base.html' %}
{% load static %}
{% load client %}
{% block title %}سرویس‌های فعال{% endblock %}
{% load jformat %}
{% block css %}
    <style>
        a, h5, tr {
            transition: all 0.3s;
        }

        tr {
            opacity: 0.8;
        }

        tr:hover {
            opacity: 1;
        }
    </style>
{% endblock %}
{% block js %}
    <!-- DATA TABLE JS-->
    <script src="{% static 'assets/plugins/datatable/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/plugins/datatable/js/dataTables.bootstrap5.js' %}"></script>
{#    <script src="{% static 'assets/plugins/datatable/js/dataTables.buttons.min.js' %}"></script>#}
{#    <script src="{% static 'assets/plugins/datatable/dataTables.responsive.min.js' %}"></script>#}
    <script src="{% static 'assets/js/table-data.js' %}"></script>
     <script>
        $(window).on('load', function () {
            let e = $('#responsive-datatable_length');
            e = e.parent();
            e.hide();
            e = $('#responsive-datatable_filter').parent();
            e.removeClass();
            e.addClass('col-12');
        });
    </script>
{% endblock %}
{% block body %}

    <!-- GLOBAL-LOADER -->
    {% comment %}{% include 'loader.html' %}{% endcomment %}
    <!-- /GLOBAL-LOADER -->

    <!-- app-Header -->
    {% include 'header.html' %}
    <!-- /app-Header -->

    <!--APP-SIDEBAR-->
    {% include 'menu.html' %}

    <!--app-content open-->
    <div class="main-content app-content mt-0">
        <div class="side-app">
            <!-- CONTAINER -->
            <div class="main-container container-fluid">
                <!-- PAGE-HEADER OPTIONAL TO WRITE SOME DATA ABOUT request.user -->
                <div class="page-header">
                    <div class="d-flex">
                        <h1 class="page-title px-2">
                            {% if request.META.HTTP_REFERER %}
                                <a href="{{ request.META.HTTP_REFERER }}">
                                    <i class="fa fa-arrow-right"></i>
                                    برگشت
                                </a>
                            {% endif %}
                        </h1>
                        <h1 class="page-title px-2">سرویس‌های فعال</h1>
                    </div>
                    <div>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{% url 'client:user_order:user_order' %}">سرویس‌های کاربر</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">سرویس‌های فعال</li>
                        </ol>
                    </div>
                </div>
                <!-- PAGE-HEADER END -->

                <!-- write your code here -->
                {% if page %}
                    <div class="row row-sm">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <div class="d-flex">
                                            <h4 class="mx-auto text-muted font-thin">صفحه‌ی {{ page.number|persian_numbers }}</h4>
                                        </div>
                                        <table class="table table-striped text-nowrap border-bottom" id="responsive-datatable">
                                            <thead>
                                                <tr>
                                                    <th class="wd-15p border-bottom-0">نام سرویس</th>
                                                    <th class="wd-10p border-bottom-0">دامنه‌ی سایت</th>
                                                    <th class="wd-10p border-bottom-0">سی</th>
    {#                                                <th class="wd-25p border-bottom-0">وضعیت سایت</th>#}
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for order_item in page %}
                                                    <tr>
                                                        <td>
                                                            <a class="text-dark" href="{% url 'order:order_detail' order_item.order.id %}">
                                                                {{ order_item.order.title }}
                                                            </a>
                                                        </td>
                                                        <td>
                                                            <a class="text-dark" href="{% url 'client:setting' %}">
                                                                {{ order_item.setting.domain }}
                                                            </a>
                                                        </td>
                                                        <td>
                                                            <a class="btn btn-primary btn-sm" href="#">
                                                                مشاهده
                                                            </a>
                                                        </td>
    {#                                                    <td>#}
    {#                                                        <div class="d-flex">#}
    {#                                                            <div class="d-flex flex-column justify-content-around">#}
    {#                                                                <h5>سایت</h5>#}
    {#                                                                {% if order_item.extra.host %}#}
    {#                                                                    <small class="text-success">هاست ساخته شده</small>#}
    {#                                                                {% else %}#}
    {#                                                                    <small class="text-danger">هاست ساخته نشده</small>#}
    {#                                                                {% endif %}#}
    {#                                                                {% if user.extra.site %}#}
    {#                                                                    <small class="text-success">سایت ساخته شده</small>#}
    {#                                                                {% else %}#}
    {#                                                                    <small class="text-danger">سایت ساخته نشده</small>#}
    {#                                                                {% endif %}#}
    {#                                                                {% if order_item.extra.order_item %}#}
    {#                                                                    <small class="text-success">یوزر ساخته شده</small>#}
    {#                                                                {% else %}#}
    {#                                                                    <small class="text-danger">یوزر ساخته نشده</small>#}
    {#                                                                {% endif %}#}
    {#                                                            </div>#}
    {#                                                        </div>#}
    {#                                                    </td>#}
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                        {% include 'pagination.html' %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <!-- /write your code here -->

            </div>
            <!-- CONTAINER END -->
        </div>
    </div>
    <!--app-content close-->


    <!-- Sidebar-right -->
    {% comment %}
    {% include 'side_bar.html' %}
    {% endcomment %}
    <!--/Sidebar-right-->

    <!-- Country-selector modal-->
    {% comment %}
    {% include 'country_selector.html' %}
    {% endcomment %}
    <!-- Country-selector modal-->

    <!-- FOOTER -->
    {% include 'footer.html' %}
    <!-- FOOTER END -->

    <!-- BACK-TO-TOP -->
    <a href="#top" id="back-to-top"><i class="fa fa-angle-up"></i></a>
{% endblock %}

templates/client/views/user_order/views/user_order_inactive.html
{% extends 'base.html' %}
{% load static %}
{% load client %}
{% block title %}سرویس‌های فعال{% endblock %}
{% load jformat %}
{% block css %}
    <style>
        a, h5, tr {
            transition: all 0.3s;
        }

        tr {
            opacity: 0.8;
        }

        tr:hover {
            opacity: 1;
        }
    </style>
{% endblock %}
{% block js %}
    <!-- DATA TABLE JS-->
    <script src="{% static 'assets/plugins/datatable/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/plugins/datatable/js/dataTables.bootstrap5.js' %}"></script>
{#    <script src="{% static 'assets/plugins/datatable/js/dataTables.buttons.min.js' %}"></script>#}
{#    <script src="{% static 'assets/plugins/datatable/dataTables.responsive.min.js' %}"></script>#}
    <script src="{% static 'assets/js/table-data.js' %}"></script>
     <script>
        $(window).on('load', function () {
            let e = $('#responsive-datatable_length');
            e = e.parent();
            e.hide();
            e = $('#responsive-datatable_filter').parent();
            e.removeClass();
            e.addClass('col-12');
        });
    </script>
{% endblock %}
{% block body %}

    <!-- GLOBAL-LOADER -->
    {% comment %}{% include 'loader.html' %}{% endcomment %}
    <!-- /GLOBAL-LOADER -->

    <!-- app-Header -->
    {% include 'header.html' %}
    <!-- /app-Header -->

    <!--APP-SIDEBAR-->
    {% include 'menu.html' %}

    <!--app-content open-->
    <div class="main-content app-content mt-0">
        <div class="side-app">
            <!-- CONTAINER -->
            <div class="main-container container-fluid">
                <!-- PAGE-HEADER OPTIONAL TO WRITE SOME DATA ABOUT request.user -->
                <div class="page-header">
                    <div class="d-flex">
                        <h1 class="page-title px-2">
                            {% if request.META.HTTP_REFERER %}
                                <a href="{{ request.META.HTTP_REFERER }}">
                                    <i class="fa fa-arrow-right"></i>
                                    برگشت
                                </a>
                            {% endif %}
                        </h1>
                        <h1 class="page-title px-2">سرویس‌های غیرفعال</h1>
                    </div>
                    <div>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{% url 'client:user_order:user_order' %}">سرویس‌های کاربر</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">سرویس‌های غیرفعال</li>
                        </ol>
                    </div>
                </div>
                <!-- PAGE-HEADER END -->

                <!-- write your code here -->
                {% if page %}
                    <div class="row row-sm">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="table-responsive">

                                        <div class="d-flex">
                                            <h4 class="mx-auto text-muted font-thin">صفحه‌ی {{ page.number|persian_numbers }}</h4>
                                        </div>
                                        <table class="table table-striped text-nowrap border-bottom" id="responsive-datatable">
                                            <thead>
                                                <tr>
                                                    <th class="wd-15p border-bottom-0">نام سرویس</th>
                                                    <th class="wd-10p border-bottom-0">دامنه‌ی سایت</th>
                                                    <th class="wd-10p border-bottom-0">سی</th>
    {#                                                <th class="wd-25p border-bottom-0">وضعیت سایت</th>#}
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for order_item in page %}
                                                    <tr>
                                                        <td>
                                                            <a class="text-dark" href="{% url 'order:order_detail' order_item.order.id %}">
                                                                {{ order_item.order.title }}
                                                            </a>
                                                        </td>
                                                        <td>
                                                            <a class="text-dark" href="{% url 'client:setting' %}">
                                                                {{ order_item.setting.domain }}
                                                            </a>
                                                        </td>
                                                        <td>
                                                            <a class="btn btn-primary btn-sm" href="#">
                                                                مشاهده
                                                            </a>
                                                        </td>
    {#                                                    <td>#}
    {#                                                        <div class="d-flex">#}
    {#                                                            <div class="d-flex flex-column justify-content-around">#}
    {#                                                                <h5>سایت</h5>#}
    {#                                                                {% if order_item.extra.host %}#}
    {#                                                                    <small class="text-success">هاست ساخته شده</small>#}
    {#                                                                {% else %}#}
    {#                                                                    <small class="text-danger">هاست ساخته نشده</small>#}
    {#                                                                {% endif %}#}
    {#                                                                {% if user.extra.site %}#}
    {#                                                                    <small class="text-success">سایت ساخته شده</small>#}
    {#                                                                {% else %}#}
    {#                                                                    <small class="text-danger">سایت ساخته نشده</small>#}
    {#                                                                {% endif %}#}
    {#                                                                {% if order_item.extra.order_item %}#}
    {#                                                                    <small class="text-success">یوزر ساخته شده</small>#}
    {#                                                                {% else %}#}
    {#                                                                    <small class="text-danger">یوزر ساخته نشده</small>#}
    {#                                                                {% endif %}#}
    {#                                                            </div>#}
    {#                                                        </div>#}
    {#                                                    </td>#}
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                        {% include 'pagination.html' %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <!-- /write your code here -->

            </div>
            <!-- CONTAINER END -->
        </div>
    </div>
    <!--app-content close-->


    <!-- Sidebar-right -->
    {% comment %}
    {% include 'side_bar.html' %}
    {% endcomment %}
    <!--/Sidebar-right-->

    <!-- Country-selector modal-->
    {% comment %}
    {% include 'country_selector.html' %}
    {% endcomment %}
    <!-- Country-selector modal-->

    <!-- FOOTER -->
    {% include 'footer.html' %}
    <!-- FOOTER END -->

    <!-- BACK-TO-TOP -->
    <a href="#top" id="back-to-top"><i class="fa fa-angle-up"></i></a>
{% endblock %}

templates/client/views/user_order/views/user_orders.html
{% extends 'base.html' %}
{% load static %}
{% block title %}سرویس‌های کاربر{% endblock %}
{% load jformat %}
{% block css %}
    <style>
        .order-hover {
            transition: 300ms;
            filter: blur(6px);
        }

        .order-hover:hover {
            filter: blur(0);
            box-shadow: 0 0 15px 5px #323254;
            color: #33c93b;
        }


    </style>
{% endblock %}
{% block js %}{% endblock %}
{% block body %}

    <!-- GLOBAL-LOADER -->
    {% comment %}{% include 'loader.html' %}{% endcomment %}
    <!-- /GLOBAL-LOADER -->

    <!-- app-Header -->
    {% include 'header.html' %}
    <!-- /app-Header -->

    <!--APP-SIDEBAR-->
    {% include 'menu.html' %}

    <!--app-content open-->
    <div class="main-content app-content mt-0">
        <div class="side-app">
            <!-- CONTAINER -->
            <div class="main-container container-fluid">
                <!-- PAGE-HEADER OPTIONAL TO WRITE SOME DATA ABOUT request.user -->
                <div class="page-header">
                    <div class="d-flex">
                        <h1 class="page-title px-2">
                            {% if request.META.HTTP_REFERER %}
                                <a href="{{ request.META.HTTP_REFERER }}">
                                    <i class="fa fa-arrow-right"></i>
                                    برگشت
                                </a>
                            {% endif %}
                        </h1>
                        <h1 class="page-title px-2">ویرایش کاربر بخش ادمین</h1>
                    </div>
                    <div>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{% url 'client:users' %}">کاربران</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">ویرایش کاربر</li>
                        </ol>
                    </div>
                </div>
                <!-- PAGE-HEADER END -->

                <!-- write your code here -->
                <div class="row d-flex align-items-center h-60vh">
                    <div class="col-12 d-flex flex-column h-100">
                        <div class="row h-100">
                            <div class="col-6">
                                <a href="{% url 'client:user_order:user_order_active' %}" class="text-light">
                                    <div class="card h-100 d-flex justify-content-center order-hover">
                                        <div class="d-flex justify-content-center">
                                            <p class="font-bold display-5">سرویس‌های فعال</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                            <div class="col-6">
                                <a href="{% url 'client:user_order:user_order_inactive' %}" class="text-light">
                                    <div class="card h-100 d-flex justify-content-center order-hover">
                                        <div class="d-flex justify-content-center">
                                            <p class="font-bold display-5">سرویس‌های غیرفعال</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /write your code here -->

            </div>
            <!-- CONTAINER END -->
        </div>
    </div>
    <!--app-content close-->


    <!-- Sidebar-right -->
    {% comment %}
    {% include 'side_bar.html' %}
    {% endcomment %}
    <!--/Sidebar-right-->

    <!-- Country-selector modal-->
    {% comment %}
    {% include 'country_selector.html' %}
    {% endcomment %}
    <!-- Country-selector modal-->

    <!-- FOOTER -->
    {% include 'footer.html' %}
    <!-- FOOTER END -->

    <!-- BACK-TO-TOP -->
    <a href="#top" id="back-to-top"><i class="fa fa-angle-up"></i></a>
{% endblock %}