client/urls.py
from django.urls import path, include
from .views import *
from .api import *

app_name = 'client'
urlpatterns = [
    path('', dashboard, name='dashboard'),

    path('profile/', profile, name='profile'),
    path('profile/password/', changepassword, name="password"),
    path('user/edit/<int:user_id>/', user_edit, name='user_edit'),

    path('setting/', user_settings, name="setting"),
    path('setting/edit/', user_settings, {'action': 'edit'}, name="setting_edit"),

    path('setting/<str:domain>/<path:path>', static_files, name="static_files"),

    path('login/', login, name='login'),
    path('verify/<str:user_cellphone>/', verify, name='verify'),
    path('logout/', Logout, name="logout"),

    path('status/', status, name="status"),

    path('users/', users, name="users"),
    path('users/<int:user_id>/active', activate_user, name='activeuser'),
    path('users/<int:user_id>/deactive', deactivate_user, name='deactiveuser'),
    path('plus_update_pass/', plus_update_pass, name="plus_update_pass"),

    path('admin/', admin, name="admin"),
    path('admin/<int:id>/', admin, name="admin"),
    path('admin/<int:id>/install/', admininstall, name="admininstall"),
    path('admin/<int:id>/install-sites/', install_sites, name="install-sites"),
    path('admin/<int:id>/remove/', adminremove, name="adminremove"),
    path('admin/<int:id>/siteuser/', check_or_createuser, name="siteuser"),
    path('admin/<str:id>/<str:user>/resetpassword/', resetpassword, name="resetpassword"),

    path('versions/', versions, name='versions'),
    path('versions/delete/<int:image_tag_id>/', version_delete, name='version_delete'),
    path('version/edit/<int:image_tag_id>/', version_edit, name='version_edit'),
    path('version/create/', version_create, name='version_create'),
    path('version/active/<int:id>/', edit_verion, {'action' : 'active'}, name="active_verion"),
    path('version/deactive/<int:id>/', edit_verion, {'action' : 'deactive'}, name="deactive_verion"),

    path('sites/', sites, name="sites"),

    # api
    path('api/select/theme/', api_select_theme, name='api_select_theme'),
    path('api/get/domain/config/<str:domain>/', api_get_domain_config, name='api_get_domain_donfig'),
    path('api/available/versions/', api_get_available_force_version, name='api_available_versions'),



    # should be moved
    path('timing/<int:user_id>/', timing, name='timing'),


    path('user/orders/', include('client.views.user_order.urls'), name='user_order'),
]

client/views/user_order/urls.py
from django.urls import path
from .views import *

app_name = 'user_order'

urlpatterns = [
    path('', user_orders, name='user_order'),
    path('user/order/active/', user_order_active, name='user_order_active'),
    path('user/order/inactive/', user_order_inactive, name='user_order_inactive')
]

order/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('', orders, name='orders'),
    path('order/create/', order_create, name='order_create'),
    path('order/edit/<int:order_id>/', order_edit, name='order_edit'),
    path('order/delete/<int:order_id>/', order_delete, name='order_delete'),
    path('order/detail/<int:order_id>/', order_detail, name='order_detail'),
    path('order/buy/<int:order_id>/', order_buy, name='order_buy'),
    path('order/buy/<int:order_id>/<int:setting_id>/', order_buy, name='order_buy'),

    path('static/files/<int:order_id>/', static_files, name='static_files')
]

vidoneplus/urls.py
from django.contrib import admin
from django.urls import path, include
from vidoneplus.views import *

urlpatterns = [
    path('', index, name="index"),
    path('validate_course/', validate_course),
    path('admin/', admin.site.urls),
    path('accounts/', include('client.urls')),
    path('course/', include('course.urls')),
    path('order/', include('order.urls')),
    path('page_not_found/', page_not_found, name='page_not_found'),
    path('page_not_found/<str:text>/', page_not_found, name='page_not_found'),
    path('page_not_found/<str:text>/<str:previous_url>/', page_not_found, name='page_not_found'),
]

client/models.py
import datetime
import jdatetime
from unidecode import unidecode
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import login


def user_image(instance, filename):
    return "%s/%s/%s" % ('setting', instance.owner.id, filename)


class User(AbstractUser):
    cellphone = models.CharField(max_length=15, unique=True)
    organization_name = models.CharField(max_length=15)
    educational_interface_name = models.CharField(max_length=200)
    description = models.TextField()
    dateofestablishment = models.DateField(null=True)
    extra = models.JSONField(default=dict)

    @staticmethod
    def get_user(username):
        user = User.objects.filter(Q(cellphone=username) | Q(email=username) | Q(username=username)).first()
        if user:
            return user
        return User()

    def save(self, *args, **kwargs):
        self.cellphone = unidecode(self.cellphone)
        self.username = self.cellphone
        super(User, self).save()

    def sendsms(self):
        if not self.cellphone:
            return False
        code = self.create_verificationcode()
        try:
            from library.smsir import Smsir
            sms = Smsir()
            sms.sendwithtemplate({'verificationCode': code}, self.cellphone, 55907)
        except (Exception, Exception):
            print('احتمالا اعتبار سامانه‌ی پیامکی تمام شده است!')
        print(code)

    def login(self, request):
        if self.is_active:
            login(request, self)
            return True
        return False

    def check_code(self, request, code):
        status = False
        if self.get_verificationcode() == code:
            status = self.login(request)
            VerificationCode.objects.filter(name=self.username).delete()
        return status

    def create_verificationcode(self):
        self.username = unidecode(self.username)
        VerificationCode.objects.filter(name=self.username).delete()
        vc = VerificationCode(name=self.username)
        vc.save()
        return str(vc.code)

    def get_verificationcode(self):
        VerificationCode.objects.filter(name=self.username, trying__gt=5).delete()
        try:
            vc = VerificationCode.objects.get(name=self.username)
            vc.trying += 1
            vc.save()
            return str(vc.code)
        except (VerificationCode.DoesNotExist, Exception):
            pass
        return None

    @staticmethod
    def check_phone_validate(self):
        prev_numbers = [
            '+93', '+355', '+213', '+1684', '+376', '+244', '+1264', '+1268', '+54', '+374', '+297',
            '+61', '+43', '+994', '+1242', '+973', '+880', '+1246', '+375', '+32', '+501', '+229',
            '+1441', '+975', '+591', '+599', '+387', '+267', '+55', '+1284', '+673', '+359', '+226',
            '+257', '+855', '+237', '+1', '+238', '+1345', '+236', '+235', '+56', '+86', '+57', '+269',
            '+243', '+242', '+682', '+506', '+225', '+385', '+53', '+599', '+357', '+420', '+45', '+246',
            '+253', '+1767', '+1809', '+1829', '+1849', '+593', '+20', '+503', '+240', '+291', '+372',
            '+268', '+251', '+500', '+298', '+679', '+358', '+33', '+594', '+689', '+241', '+220', '+995',
            '+49', '+233', '+350', '+30', '+299', '+1473', '+590', '+1671', '+502', '+224', '+245',
            '+592', '+509', '+504', '+852', '+36', '+354', '+91', '+62', '+98', '+964', '+353', '+972',
            '+39', '+1876', '+81', '+962', '+7', '+254', '+686', '+383', '+965', '+996', '+856', '+371',
            '+961', '+266', '+231', '+218', '+423', '+370', '+352', '+853', '+261', '+265', '+60', '+960',
            '+223', '+356', '+692', '+596', '+222', '+230', '+52', '+691', '+373', '+377', '+976', '+382',
            '+1664', '+212', '+258', '+95', '+264', '+674', '+977', '+31', '+687', '+64', '+505', '+227',
            '+234', '+683', '+672', '+850', '+389', '+1670', '+47', '+968', '+92', '+680', '+970', '+507',
            '+675', '+595', '+51', '+63', '+48', '+351', '+1787', '+1939', '+974', '+262', '+40', '+7',
            '+250', '+247', '+290', '+1869', '+1758', '+508', '+1784', '+685', '+378', '+239', '+966',
            '+221', '+381', '+248', '+232', '+65', '+1721', '+421', '+386', '+677', '+252', '+27', '+82',
            '+211', '+34', '+94', '+249', '+597', '+46', '+41', '+963', '+886', '+992', '+255', '+66',
            '+670', '+228', '+690', '+676', '+1868', '+216', '+90', '+993', '+1649', '+688', '+256',
            '+380', '+971', '+44', '+598', '+1340', '+1', '+998', '+678', '+58', '+84', '+681', '+967',
            '+260', '+263'
        ]
        if self.cellphone:
            prev = self.cellphone[:-10]
            if prev in prev_numbers:
                return True
        return False

    def get_status(self):
        return self.status

    @staticmethod
    def not_empty(request, request_method, *args):
        if request_method == 'POST':
            for input_name in args:
                if not request.POST.get(input_name):
                    return False
        else:
            for input_name in args:
                if not request.GET.get(input_name):
                    return False
        return True

    @staticmethod
    def str_to_date(string_date):
        d = datetime.datetime.strptime(string_date, '%Y/%m/%d').date()
        return jdatetime.date(d.year, d.month, d.day).togregorian()


class VerificationCode(models.Model):
    name = models.CharField(max_length=100, primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    code = models.IntegerField()
    trying = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        import random
        if not self.code:
            self.code = random.randint(1000, 9999)
        super(VerificationCode, self).save()


class Imagetag(models.Model):
    status = models.BooleanField(default=True)
    forceupdate = models.BooleanField(default=False)
    pwa_version = models.CharField(max_length=20)
    pwa_description = models.CharField(max_length=200)
    admin_version = models.CharField(max_length=20)
    admin_description = models.CharField(max_length=200)
    site_version = models.CharField(max_length=20)
    site_description = models.CharField(max_length=200)
    android_version = models.CharField(max_length=20)
    android_description = models.CharField(max_length=200)
    ios_version = models.CharField(max_length=20)
    ios_description = models.CharField(max_length=200)


class Setting(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    org_color = models.CharField(max_length=50)
    sub_color = models.CharField(max_length=50)
    app_name = models.CharField(max_length=250)
    domain = models.CharField(max_length=50)
    kuberid = models.CharField(max_length=250, null=True, blank=True)
    site_name = models.CharField(max_length=250, null=True, blank=True)
    admin_name = models.CharField(max_length=250, null=True, blank=True)
    pwa_name = models.CharField(max_length=250, null=True, blank=True)
    fullname = models.CharField(max_length=250, null=True, blank=True)
    contact_phone = models.CharField(max_length=250)
    download_link = models.CharField(max_length=500)
    company_logo = models.ImageField(upload_to=user_image)
    splashscreen = models.ImageField(upload_to=user_image)
    image_tag = models.ForeignKey(Imagetag, on_delete=models.CASCADE, null=True)
    instagram = models.CharField(max_length=50, null=True, blank=True)
    aparat = models.CharField(max_length=50, null=True, blank=True)
    facebook = models.CharField(max_length=50, null=True, blank=True)
    twitter = models.CharField(max_length=70, null=True, blank=True)
    youtube = models.CharField(max_length=70, null=True, blank=True)
    favicon = models.ImageField(upload_to=user_image)
    short_title = models.CharField(max_length=50, null=True, blank=True)
    slogan = models.CharField(max_length=50, null=True, blank=True)
    zarinpal = models.CharField(max_length=50, null=True, blank=True)
    smsir_key = models.CharField(max_length=50, null=True, blank=True)

    def get_splashscreen(self):
        return self.splashscreen.path.split('/')[-1]

    def get_company_logo(self):
        return self.company_logo.path.split('/')[-1]

    def get_favicon(self):
        return self.favicon.path.split('/')[-1]


# class CourseVitrin(models.Model):
#     title = models.CharField(max_length=200)
#     description = models.TextField()
#     price = models.BigIntegerField()
#     price_with_discount = models.BigIntegerField(default=0)
#     teacher = models.CharField(max_length=200)
#     lesson_count = models.IntegerField(default=0)
#
#     def save(self, *args, **kwargs):
#         super(CourseVitrin, self).save()
#
#     def buyed(self, user):
#         try:
#             CourseUser.objects.get(course=self, user=user)
#             return True
#         except:
#             return False


class Status(models.Model):
    active_user = models.BooleanField(default=False)
    site_created = models.BooleanField(default=False)
    duration = models.IntegerField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)


# class CourseUser(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     course = models.ForeignKey(Course, on_delete=models.CASCADE)
#     status = models.BooleanField(default=False)

class PasswordGenerator(models.Model):
    setting = models.ForeignKey(Setting, on_delete=models.CASCADE)
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)

client/views/activeuser.py
from django.contrib.auth.models import User
from library.smsir import Smsir
from .imports import *
from ..models import *
from client.decorators import allowed_users


@login_required
@allowed_users(allowed_roles=['admin'])
def activate_user(request, user_id):
    context = {}
    non_staff_users = User.objects.filter(is_staff=False)
    context['users'] = non_staff_users
    context['status'] = Status.objects.filter(user__in=non_staff_users)
    context['user'] = User.objects.get(id=user_id)
    context['cellphone'] = User.objects.get(id=user_id).cellphone
    status = Status.objects.get(user=context['user'])
    status.active_user = True
    status.save()
    sms = Smsir()
    sms.sendsms('اکانت شما در ویدان فعال شد.', context['cellphone'])
    context['msg'] = "کاربر  %s تایید شد" % (context['user'].first_name + " " + context['user'].last_name)
    return render(request, f"{app_name.name}/{__name__.split('.')[-1]}.html", context)

client/views/admin.py
from .imports import *


@login_required
@allowed_users(allowed_roles=['admin'])
def admin(request):
    context = {'settings': Setting.objects.all()}
    return render(request, f"{app_name.name}/{__name__.split('.')[-1]}.html", context)

client/views/courses.py
from .imports import *
from ..models import *


@login_required
def courses(request):
    context = {}
    context['courses'] = CourseVitrin.objects.all()
    if request.method == 'POST':
        context['user'] = request.user
        countcheck = request.POST.getlist('course_records')
        for item in countcheck:
            cu = CourseUser()
            cu.course = CourseVitrin.objects.get(id=item)
            cu.user = User.objects.get(id=request.user.id)
            cu.status = True
            cu.save()
    # context['all_cu'] = CourseUser.objects.filter(user=request.user)
    return render(request, "client/course.html", context)

client/views/dashboard.py
from .imports import *
from ..models import Setting as Usetting, Status


@login_required
def dashboard(request):
    context = {}
    try:
        context['settings'] = Usetting.objects.get(owner=request.user).domain
        context['status'] = Status.objects.get(user=request.user).site_created
        if not context['settings']:
            context['msg'] = "شما هنوز دامنه ای ثبت نکرده اید"
        if not context['status']:
            context['site'] = False
    except (Exception, Exception):
        pass
    return render(request, f'{__name__.replace("views.", "").replace(".", "/")}.html', context)

client/views/deactivate_user.py
from .imports import *


@login_required
@allowed_users(allowed_roles=['admin'])
def deactivate_user(request, user_id):
    context = {}
    context['users'] = User.objects.filter(is_staff=False)
    context['status'] = Status.objects.filter(user__in=User.objects.filter(is_staff=False))
    context['user'] = User.objects.get(id=user_id)
    status = Status.objects.get(user=context['user'])
    status.active_user = 0
    status.save()
    context['msg'] = "کاربر  %s غیرفعال شد" % (context['user'].first_name + " " + context['user'].last_name)
    return render(request, 'client/activeuser.html', context)

client/views/login.py
from .imports import *


def login(request):
    context = {}
    if request.user.is_authenticated:
        return HttpResponseRedirect("/")
    context['error'] = 0
    if request.method == 'POST':
        context['request'] = {}
        context['request']['cellphone'] = request.POST.get('cellphone', '').strip()
        pattern = re.compile("^09?\d{9}$", re.IGNORECASE)
        if pattern.match(context['request']['cellphone']):
            context['request']['cellphone'] = "+989" + context['request']['cellphone'][2:]
            cellphone = context['request']['cellphone']
            return redirect(reverse('client:verify', kwargs={'user_cellphone': cellphone}))
    return render(request, f'{__name__.replace("views.", "").replace(".", "/")}.html', context)

client/views/logout.py
from .imports import *


@login_required
def Logout(request):
    logout(request)
    return HttpResponseRedirect("/")

templates/client/user_edit.html
{% extends 'base.html' %}
{% load static %}{% load jformat %}
{% block title %}ویرایش کاربر{% endblock %}
{% block css %}
    <!-- jquery date picker css -->
    <link rel="stylesheet" href="{% static 'assets/plugins/jquery_persian_datepicker/kamadatepicker.min.css' %}">
{% endblock %}
{% block js %}
    <!-- jquery date picker js -->
    <script src="{% static 'assets/plugins/jquery_persian_datepicker/kamadatepicker.js' %}"></script>

    <!-- SWEET-ALERT JS -->
    <script src="{% static 'assets/plugins/sweet-alert/sweetalert.min.js' %}"></script>
    <script src="{% static 'assets/js/sweet-alert.js' %}"></script>
    <script>
        {% if save %}
            swal({
            type: "success",
            title: "تغییرات با موفقیت ذخیره شدند!",
            confirmButtonText: 'باشه',
            timer: 600
        });
        {% endif %} 
        kamaDatepicker('date', {
            markHolidays: true,
            markToday: true,
            gotoToday: true,
            twodigit: true,
            highlightSelectedDay: 'true',
            sync: true,
        });
    </script>
{% endblock %}

{% block body %}

    <!-- app-Header -->
    {% include 'header.html' %}
    <!-- /app-Header -->

    <!--APP-SIDEBAR-->
    {% include 'menu.html' %}


    <!--app-content open-->
    <div class="main-content app-content mt-0">
        <div class="side-app">
            <!-- CONTAINER -->
            <div class="main-container container-fluid">
                <!-- PAGE-HEADER OPTIONAL TO WRITE SOME DATA ABOUT request.user -->
                <div class="page-header">
                    <div class="d-flex">
                        <h1 class="page-title px-2">
                            {% if request.META.HTTP_REFERER %}
                                <a href="{{ request.META.HTTP_REFERER }}">
                                    <i class="fa fa-arrow-right"></i>
                                    برگشت
                                </a>
                            {% endif %}
                        </h1>
                        <h1 class="page-title px-2">ویرایش کاربر بخش ادمین</h1>
                    </div>
                    <div>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{% url 'client:users' %}">کاربران</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">ویرایش کاربر</li>
                        </ol>
                    </div>
                </div>
                <!-- PAGE-HEADER END -->

                <!-- write your code here -->
                <form action="{% url 'client:user_edit' user.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                    <div class="col-md-12 col-xl-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                    اطلاعات کاربر
                                    {{ user.first_name }} {{ user.last_name }}
                                </h3>
                            </div>
                            <div class="card-body">
                                <div class="form-row">
                                    <div class="form-group col-md-6 mb-0">
                                        <div class="form-group">
                                            <label for="first_name" class="form-label h5">نام</label>
                                            <input type="text" id="first_name" value="{{ user.first_name }}" class="form-control" placeholder="نام" name="first_name">
                                        </div>
                                    </div>
                                    <div class="form-group col-md-6 mb-0">
                                        <div class="form-group">
                                            <label for="last_name" class="form-label h5">نام خانوادگی</label>
                                            <input type="text" id="last_name" value="{{ user.last_name }}" class="form-control" placeholder="نام خانوادگی" name="last_name">
                                        </div>
                                    </div>


                                    <div class="form-group col-md-6 mb-0">
                                        <div class="form-group ">
                                            <label for="organization_name" class="form-label h5">نام شرکت</label>
                                            <input id="organization_name" type="text" value="{{ user.organization_name }}" class="form-control" placeholder="نام شرکت" name="organization_name">
                                        </div>
                                    </div>

                                    <div class="form-group col-md-6 mb-0">
                                        <div class="form-group">
                                            <label for="date" class="form-label h5">تاریخ ثبت شرکت</label>
                                            <input class="form-control number-font" value="{{ user.dateofestablishment|jformat:'%Y/%m/%d' }}" autocomplete="off" placeholder="تاریخ ثبت شرکت" id="date" name="dateofestablishment" type="text">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6 mb-0">
                                        <div class="form-group ">
                                            <label for="email" class="form-label h5">ایمیل</label>
                                            <input id="email" type="email" value="{{ user.email }}" class="form-control" placeholder="ایمیل" name="email">
                                        </div>
                                    </div>
                                    <div class="form-group col-md-6 mb-0">
                                        <div class="form-group">
                                            <label for="educational_interface_name" class="form-label h5">روابط آموزشی</label>
                                            <input id="educational_interface_name" type="text" value="{{ user.educational_interface_name }}" class="form-control" placeholder="روابط آموزشی" name="educational_interface_name">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-12 mb-0">
                                        <div class="form-group">
                                            <label for="description" class="form-label h5">توضیحات</label>
                                            <textarea id="description" class="form-control mb-4" rows="4" name="description" placeholder="توضیحات">{{ user.description }}</textarea>
                                        </div>
                                    </div>
                                    <div class="form-group col-md-6 mb-0">
                                        <div class="form-group">
                                            <label class="custom-control custom-radio-md">
                                                <input type="radio" class="custom-control-input" name="status"
                                                       value="True" {% if user.status.active_user %}checked=""{% endif %}>
                                                <span class="custom-control-label">فعال</span>
                                            </label>
                                            <label class="custom-control custom-radio-md">
                                                <input type="radio" class="custom-control-input" name="status"
                                                       value="False" {% if not user.status.active_user %}checked=""{% endif %}>
                                                <span class="custom-control-label">غیرفعال</span>
                                            </label>
                                        </div>
                                    </div>
                                    {% if request.user.is_superuser %}
                                        <div class="form-group col-md-6 mb-0">
                                            <div class="form-group h-100">
                                                <div class="d-flex justify-content-around align-items-center h-100">
                                                    {% if user.setting_set.first.domain %}
                                                        <a href="{% url 'client:admininstall' user.setting_set.first.owner.id %}"
                                                           class="btn {% if user.extra.host %}btn-success disabled{% else %}btn-outline-primary{% endif %}"
                                                           {% if user.extra.host %}disabled="" {% endif %}>
                                                            ساخت هاست
                                                        </a>
                                                        {% if user.extra.host %}
                                                            <a href="{% url 'client:install-sites' user.setting_set.first.owner.id %}"
                                                               class="btn {% if user.extra.site %}btn-success disabled{% else %}btn-outline-primary{% endif %}"
                                                               {% if user.extra.host %}disabled="" {% endif %}>
                                                                ساخت سایت
                                                            </a>
                                                            {% if user.extra.site %}
                                                                <a href="{% url 'client:siteuser' user.setting_set.first.owner.id %}"
                                                                   class="btn {% if user.extra.user %}btn-success disabled{% else %}btn-outline-primary{% endif %}"
                                                                   {% if user.extra.user %}disabled="" {% endif %}>
                                                                    یوزر
                                                                </a>
                                                            {% endif %}
                                                        {% endif %}
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="form-footer mt-2">
                                    <button type="submit" class="btn btn-primary">ثبت</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </form>

                <!-- /write your code here -->
            </div>
            <!-- CONTAINER END -->
        </div>
    </div>
    <!--app-content close-->


    <!-- Sidebar-right -->
{#    {% include 'side_bar.html' %}#}
    <!--/Sidebar-right-->

    <!-- Country-selector modal-->
{#    {% include 'country_selector.html' %}#}
    <!-- Country-selector modal-->

    <!-- FOOTER -->
    {% include 'footer.html' %}
    <!-- FOOTER END -->

    <!-- BACK-TO-TOP -->
    <a href="#top" id="back-to-top"><i class="fa fa-angle-up"></i></a>
{% endblock %}