client/urls.py
from django.urls import path, include
from .views import *
from .api import *

app_name = 'client'
urlpatterns = [
    path('', dashboard, name='dashboard'),

    path('profile/', profile, name='profile'),
    path('profile/password/', changepassword, name="password"),
    path('user/edit/<int:user_id>/', user_edit, name='user_edit'),

    path('setting/', user_settings, name="setting"),
    path('setting/edit/', user_settings, {'action': 'edit'}, name="setting_edit"),

    path('setting/<str:domain>/<path:path>', static_files, name="static_files"),

    path('login/', login, name='login'),
    path('verify/<str:user_cellphone>/', verify, name='verify'),
    path('logout/', Logout, name="logout"),

    path('status/', status, name="status"),

    path('users/', users, name="users"),
    path('users/<int:user_id>/active', activate_user, name='activeuser'),
    path('users/<int:user_id>/deactive', deactivate_user, name='deactiveuser'),
    path('plus_update_pass/', plus_update_pass, name="plus_update_pass"),

    path('admin/', admin, name="admin"),
    path('admin/<int:id>/', admin, name="admin"),
    path('admin/<int:id>/install/', admininstall, name="admininstall"),
    path('admin/<int:id>/install-sites/', install_sites, name="install-sites"),
    path('admin/<int:id>/remove/', adminremove, name="adminremove"),
    path('admin/<int:id>/siteuser/', check_or_createuser, name="siteuser"),
    path('admin/<str:id>/<str:user>/resetpassword/', resetpassword, name="resetpassword"),

    path('versions/', versions, name='versions'),
    path('versions/delete/<int:image_tag_id>/', version_delete, name='version_delete'),
    path('version/edit/<int:image_tag_id>/', version_edit, name='version_edit'),
    path('version/create/', version_create, name='version_create'),
    path('version/active/<int:id>/', edit_verion, {'action' : 'active'}, name="active_verion"),
    path('version/deactive/<int:id>/', edit_verion, {'action' : 'deactive'}, name="deactive_verion"),

    path('sites/', sites, name="sites"),

    # api
    path('api/select/theme/', api_select_theme, name='api_select_theme'),
    path('api/get/domain/config/<str:domain>/', api_get_domain_config, name='api_get_domain_donfig'),
    path('api/available/versions/', api_get_available_force_version, name='api_available_versions'),



    # should be moved
    path('timing/<int:user_id>/', timing, name='timing'),


    path('user/orders/', include('client.views.user_order.urls'), name='user_order'),
]

order/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('', orders, name='orders'),
    path('order/create/', order_create, name='order_create'),
    path('order/edit/<int:order_id>/', order_edit, name='order_edit'),
    path('order/delete/<int:order_id>/', order_delete, name='order_delete'),
    path('order/detail/<int:order_id>/', order_detail, name='order_detail'),
    path('order/buy/<int:order_id>/', order_buy, name='order_buy'),
    path('order/buy/<int:order_id>/<int:setting_id>/', order_buy, name='order_buy'),

    path('static/files/<int:order_id>/', static_files, name='static_files')
]

vidoneplus/urls.py
from django.contrib import admin
from django.urls import path, include
from vidoneplus.views import *

urlpatterns = [
    path('', index, name="index"),
    path('validate_course/', validate_course),
    path('admin/', admin.site.urls),
    path('accounts/', include('client.urls')),
    path('course/', include('course.urls')),
    path('order/', include('order.urls')),
    path('page_not_found/', page_not_found, name='page_not_found'),
    path('page_not_found/<str:text>/', page_not_found, name='page_not_found'),
    path('page_not_found/<str:text>/<str:previous_url>/', page_not_found, name='page_not_found'),
]

templates/404_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}صفحه پیدا نشد!{% endblock %}
{% load jformat %}
{% block css %}{% endblock %}
{% block js %}{% endblock %}
{% block body %}

    <!-- GLOBAL-LOADER -->
    {% comment %}{% include 'loader.html' %}{% endcomment %}
    <!-- /GLOBAL-LOADER -->

    <!-- app-Header -->
    {% comment %}{% include 'header.html' %}{% endcomment %}
    <!-- /app-Header -->

    <!--APP-SIDEBAR-->
    {% comment %}{% include 'menu.html' %}{% endcomment %}

    <!--app-content open-->


    <body class="app sidebar-mini rtl dark-mode" style="overflow: hidden;">

        <!-- PAGE -->
        <div class="page">
            <div class="page-main" style="
                  background-image: url('{% static 'assets/images/svgs/error_pages/404 error with person looking for-amico.svg' %}');
                  background-repeat: no-repeat;
                  background-position: center;
                  ">
                <div class="container">
                    <div class="row justify-content-center align-items-end" style="height: 80vh">
                        <div class="col-12">
                            {% if text %}
                                <div class="row justify-content-center">
                                    <h4>ما خیلی متاسفیم که این اتفاق افتاد!</h4>
                                </div>
                                <div class="row justify-content-center">
                                    <h4>{{ text }}</h4>
                                </div>
                            {% else %}
                                <div class="row justify-content-center">
                                    <h4>لطفا به صفحه‌ی اصلی برگردین</h4>
                                </div>
                            {% endif %}
                            <div class="row justify-content-center">
                                <a class="btn btn-outline-light" href="{{ previous_url }}">برگشت</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>

    <!--app-content close-->


    <!-- Sidebar-right -->
    {% comment %}
    {% include 'side_bar.html' %}
    {% endcomment %}
    <!--/Sidebar-right-->

    <!-- Country-selector modal-->
    {% comment %}
    {% include 'country_selector.html' %}
    {% endcomment %}
    <!-- Country-selector modal-->

    <!-- FOOTER -->
    {% comment %}{% include 'footer.html' %}{% endcomment %}
    <!-- FOOTER END -->

    <!-- BACK-TO-TOP -->
    <a href="#top" id="back-to-top"><i class="fa fa-angle-up"></i></a>
{% endblock %}

templates/base.html
<!doctype html>{% load static %}
<html lang="fa" dir="rtl">
<head>

    <!-- META DATA -->
    <meta charset="UTF-8">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Sash – Bootstrap 5  Admin & Dashboard Template">
    <meta name="author" content="Spruko Technologies Private Limited">
    <meta name="keywords" content="admin,admin dashboard,admin panel,admin template,bootstrap,clean,dashboard,flat,jquery,modern,responsive,premium admin templates,responsive admin,ui,ui kit.">

    <!-- FAVICON -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/images/brand/favicon.ico' %}" />

    <!-- TITLE -->
    <title>ویدان‌پلاس - {% block title %}{% endblock %}</title>

    <!-- BOOTSTRAP CSS -->
    <link id="style" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}"  rel="stylesheet" />

    <!-- STYLE CSS -->
    <link href="{% static 'assets/css/style.css' %}"  rel="stylesheet" />
    <link href="{% static 'assets/css/dark-style.css' %}"  rel="stylesheet" />
    <link href="{% static 'assets/css/transparent-style.css' %}"  rel="stylesheet">
    <link href="{% static 'assets/css/skin-modes.css' %}"  rel="stylesheet" />

    <!--- FONT-ICONS CSS -->
    <link href="{% static 'assets/css/icons.css' %}"  rel="stylesheet" />

    <!-- COLOR SKIN CSS -->
    <link id="theme" rel="stylesheet" type="text/css" media="all" href="{% static 'assets/colors/color1.css' %}" />

    <!-- TOASTIFY JS -->
    <link rel="stylesheet" href="{% static 'assets/plugins/toastify/toastify.css' %}">

    <!-- CUSTOM IRANSANSX FONTS -->
    <link rel="stylesheet" href="{% static 'assets/css/font_style.css' %}">

    <!-- CUSTOM HEIGHT SIZING -->
    <link rel="stylesheet" href="{% static 'assets/css/vh_sizing.css' %}">


    {% block css %}{% endblock %}

</head>

<body class="app sidebar-mini rtl {% if request.user.extra.dark_mode %}dark-mode{% endif %}">

    <!-- PAGE -->
    <div class="page">
        <div class="page-main">
            <!--app-content open-->
            {% block body %}{% endblock %}
            <!--app-content close-->
        </div>
    </div>

    <!-- JQUERY JS -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>

    <!-- BOOTSTRAP JS -->
    <script src="{% static 'assets/plugins/bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- SIDEBAR JS -->
    {% comment %}
    <script src="{% static 'assets/plugins/sidebar/sidebar.js' %}"></script>
    {% endcomment %}


    <!-- Perfect SCROLLBAR JS-->
    <script src="{% static 'assets/plugins/p-scroll/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'assets/plugins/p-scroll/pscroll.js' %}"></script>

    <!-- INTERNAL SELECT2 JS -->
    <script src="{% static 'assets/plugins/select2/select2.full.min.js' %}"></script>

    <!-- Sticky js -->
    <script src="{% static 'assets/js/sticky.js' %}"></script>

    <!-- SIDEBAR JS -->
    <script src="{% static 'assets/plugins/sidebar/sidebar.js' %}"></script>

    <!-- SIDE-MENU JS-->
    <script src="{% static 'assets/plugins/sidemenu/sidemenu.js' %}"></script>

    <!-- SWEET-ALERT JS -->
    <script src="{% static 'assets/plugins/sweet-alert/sweetalert.min.js' %}"></script>
    <script src="{% static 'assets/js/sweet-alert.js' %}"></script>

    <!-- TOASTIFY JS -->
    <script src="{% static 'assets/plugins/toastify/toastify.js' %}"></script>

    <script>
        let lay_out_set = $('.light-layout, .dark-layout');
        lay_out_set.on('click', function () {
            $(this).addClass('active');
            lay_out_set.not($(this)).removeClass('active');
            let text = '';
            let mode = 'dark';
            text = 'تم تاریک شد'
            if ($(this).hasClass('light-layout')) {
                text = 'تم روشن شد'
                mode = 'light';
            }
            $.ajax({
                url: '{% url 'client:api_select_theme' %}',
                type: 'GET',
                data: {'mode': mode},
                success: function () {
                    Toastify({
                        text: text,
                        duration: 1500,
                        newWindow: true,
                        close: true,
                        gravity: 'top', // `top` or `bottom`
                        position: 'center', // `left`, `center` or `right`
                        stopOnFocus: true, // Prevents dismissing of toast on hover
                        style: {
                            background: 'rgb(108,95,252)',
                        },
                        onClick: function () {} // Callback after click
                    }).showToast();
                },
            });
        });
    </script>

    {% block js %}{% endblock %}

    <!-- Sticky js -->
    <script src="{% static 'assets/js/select2.js' %}"></script>

    <!-- CUSTOM JS -->
    <script src="{% static 'assets/js/custom.js' %}"></script>
</body>

</html>

templates/bhtml.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% load jformat %}
{% block css %}{% endblock %}
{% block js %}{% endblock %}
{% block body %}

    <!-- GLOBAL-LOADER -->
    {% include 'loader.html' %}
    <!-- /GLOBAL-LOADER -->

    <!-- app-Header -->
    {% include 'header.html' %}
    <!-- /app-Header -->

    <!--APP-SIDEBAR-->
    {% include 'menu.html' %}

    <!--app-content open-->
    <div class="main-content app-content mt-0">
        <div class="side-app">
            <!-- CONTAINER -->
            <div class="main-container container-fluid">
                <!-- PAGE-HEADER OPTIONAL TO WRITE SOME DATA ABOUT request.user -->
                <div class="page-header">
                    <div class="d-flex">
                        <h1 class="page-title px-2">
                            {% if request.META.HTTP_REFERER %}
                                <a href="{{ request.META.HTTP_REFERER }}">
                                    <i class="fa fa-arrow-right"></i>
                                    برگشت
                                </a>
                            {% endif %}
                        </h1>
                        <h1 class="page-title px-2">ویرایش کاربر بخش ادمین</h1>
                    </div>
                    <div>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{% url 'client:users' %}">کاربران</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">ویرایش کاربر</li>
                        </ol>
                    </div>
                </div>
                <!-- PAGE-HEADER END -->

                <!-- write your code here -->
                hello world
                <!-- /write your code here -->

            </div>
            <!-- CONTAINER END -->
        </div>
    </div>
    <!--app-content close-->


    <!-- Sidebar-right -->
    {% comment %}
    {% include 'side_bar.html' %}
    {% endcomment %}
    <!--/Sidebar-right-->

    <!-- Country-selector modal-->
    {% comment %}
    {% include 'country_selector.html' %}
    {% endcomment %}
    <!-- Country-selector modal-->

    <!-- FOOTER -->
    {% include 'footer.html' %}
    <!-- FOOTER END -->

    <!-- BACK-TO-TOP -->
    <a href="#top" id="back-to-top"><i class="fa fa-angle-up"></i></a>
{% endblock %}

templates/country_selector.html
{% load static %}
<div class="modal fade" id="country-selector">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content country-select-modal">
            <div class="modal-header">
                <h6 class="modal-title">Choose Country</h6><button aria-label="Close" class="btn-close"
                    data-bs-dismiss="modal" type="button"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                <ul class="row p-3">
                    <li class="col-lg-6 mb-2">
                        <a href="javascript:void(0)" class="btn btn-country btn-lg btn-block active">
                            <span class="country-selector"><img alt="" src="{% static 'assets/images/flags/us_flag.jpg' %}"
                                    class="me-3 language"></span>USA
                        </a>
                    </li>
                    <li class="col-lg-6 mb-2">
                        <a href="javascript:void(0)" class="btn btn-country btn-lg btn-block">
                            <span class="country-selector"><img alt=""
                                src="{% static 'assets/images/flags/italy_flag.jpg' %}"
                                class="me-3 language"></span>Italy
                        </a>
                    </li>
                    <li class="col-lg-6 mb-2">
                        <a href="javascript:void(0)" class="btn btn-country btn-lg btn-block">
                            <span class="country-selector"><img alt=""
                                src="{% static 'assets/images/flags/spain_flag.jpg' %}"
                                class="me-3 language"></span>Spain
                        </a>
                    </li>
                    <li class="col-lg-6 mb-2">
                        <a href="javascript:void(0)" class="btn btn-country btn-lg btn-block">
                            <span class="country-selector"><img alt=""
                                src="{% static 'assets/images/flags/india_flag.jpg' %}"
                                class="me-3 language"></span>India
                        </a>
                    </li>
                    <li class="col-lg-6 mb-2">
                        <a href="javascript:void(0)" class="btn btn-country btn-lg btn-block">
                            <span class="country-selector"><img alt=""
                                src="{% static 'assets/images/flags/french_flag.jpg' %}"
                                class="me-3 language"></span>French
                        </a>
                    </li>
                    <li class="col-lg-6 mb-2">
                        <a href="javascript:void(0)" class="btn btn-country btn-lg btn-block">
                            <span class="country-selector"><img alt=""
                                src="{% static 'assets/images/flags/russia_flag.jpg' %}"
                                class="me-3 language"></span>Russia
                        </a>
                    </li>
                    <li class="col-lg-6 mb-2">
                        <a href="javascript:void(0)" class="btn btn-country btn-lg btn-block">
                            <span class="country-selector"><img alt=""
                                src="{% static 'assets/images/flags/germany_flag.jpg' %}"
                                class="me-3 language"></span>Germany
                        </a>
                    </li>
                    <li class="col-lg-6 mb-2">
                        <a href="javascript:void(0)" class="btn btn-country btn-lg btn-block">
                            <span class="country-selector"><img alt=""
                                src="{% static 'assets/images/flags/argentina.jpg' %}"
                                class="me-3 language"></span>Argentina
                        </a>
                    </li>
                    <li class="col-lg-6 mb-2">
                        <a href="javascript:void(0)" class="btn btn-country btn-lg btn-block">
                            <span class="country-selector"><img alt="" src="{% static 'assets/images/flags/malaysia.jpg' %}"
                                class="me-3 language"></span>Malaysia
                        </a>
                    </li>
                    <li class="col-lg-6 mb-2">
                        <a href="javascript:void(0)" class="btn btn-country btn-lg btn-block">
                            <span class="country-selector"><img alt="" src="{% static 'assets/images/flags/turkey.jpg' %}"
                                class="me-3 language"></span>Turkey
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

templates/footer.html
{% load static %}
<footer class="footer">
    <div class="container">
        <div class="row align-items-center flex-row-reverse">
            <div class="col-md-12 col-sm-12 text-center">
                Copyright © 2022 <a href="javascript:void(0)">Novinparva</a>
                {#                        . Designed with #}
                {#                        <span class="fa fa-heart text-danger"></span> by <a href="javascript:void(0)"> Spruko </a> All rights reserved.#}
            </div>
        </div>
    </div>
</footer>

templates/left_time.html
<!-- uses /static/assets/js/left_time/LeftTime.js -->
<!-- uses Bootstrap 5 and later -->


<!-- left time -->
<div class="card p-2">
    <div class="d-flex justify-content-around">
        <div class="h3">
            زمان باقی‌مانده
        </div>
    </div>

    <div class="d-flex justify-content-around">
        <div class="d-flex flex-column justify-content-center">
            <div class="mx-auto">
                <div class="h3" id="left_second"></div>
            </div>
            <div class="mx-auto h4 text-muted">
                ثانیه
            </div>
        </div>

        <div class="d-flex justify-content-center">
            <div class="mx-auto h1 text-muted">
                :
            </div>
        </div>

        <div class="d-flex flex-column justify-content-center">
            <div class="mx-auto">
                <div class="h3" id="left_minute"></div>
            </div>
            <div class="mx-auto h4 text-muted">
                دقیقه
            </div>
        </div>

        <div class="d-flex justify-content-center">
            <div class="mx-auto h1 text-muted">
                :
            </div>
        </div>

        <div class="d-flex flex-column justify-content-center">
            <div class="mx-auto">
                <div class="h3" id="left_hour"></div>
            </div>
            <div class="mx-auto h4 text-muted">
                ساعت
            </div>
        </div>
    </div>

    {#                                <div id="left_hour"></div>#}
    {#                                <div id="left_minute"></div>#}
    {#                                <div id="left_second"></div>#}
</div>

templates/live_date.html
<div class="d-flex justify-content-center">
    {# <div class="h3" id="date"></div>#}
    <h1 class="page-title px-2" id="date"></h1>
</div>

templates/live_time.html
{% load static %}
{% block js %}
    <script data-name="clock">
        window.addEventListener('load', function () {
            let live_date = $('#date');
            let live_hour = $('#live_hours');
            let live_minutes = $('#live_minutes');
            let live_seconds = $('#live_seconds');
            let now;
            let date;

            function refresh_time() {
                now = new Date()
                date = Intl.DateTimeFormat('fa-u-ca-persian', {dateStyle: 'full'}).format(now);
                let hour = (now.getHours() < 10 ? '0' : '') + now.getHours().toLocaleString();
                let minute = (now.getMinutes() < 10 ? '0' : '') + now.getMinutes().toLocaleString();
                let second = (now.getSeconds() < 10 ? '0' : '') + now.getSeconds().toLocaleString();
                live_date.html(date);
                live_hour.html(hour);
                live_minutes.html(minute);
                live_seconds.html(second);
            }

            setInterval(refresh_time, 1000);
        });
    </script>
{% endblock %}
<div class="d-flex justify-content-around">
    <div class="d-flex flex-column justify-content-center">
        <div class="mx-auto">
            <div id="live_seconds"></div>
        </div>
        {#            <div class="mx-auto h4 text-muted">#}
        {#                ثانیه#}
        {#            </div>#}
    </div>

    <div class="d-flex flex-column justify-content-center mx-1 text-muted">
        :
    </div>

    <div class="d-flex flex-column justify-content-center">
        <div class="mx-auto">
            <div id="live_minutes"></div>
        </div>
        {#            <div class="mx-auto h4 text-muted">#}
        {#                دقیقه#}
        {#            </div>#}
    </div>

    <div class="d-flex flex-column justify-content-center mx-1 text-muted">
        :
    </div>

    <div class="d-flex flex-column justify-content-center">
        <div class="mx-auto">
            <div id="live_hours"></div>
        </div>
        {#            <div class="mx-auto h4 text-muted">#}
        {#                ساعت#}
        {#            </div>#}
    </div>
</div>

templates/loader.html
{% load static %}
<!-- GLOBAL-LOADER -->
<div id="global-loader" style="background-color: #0f081e">
    <img src="{% static 'assets/images/brand/vidoneplus_mainlogo.png' %}" class="loader-img" alt="Loader">
</div>
<!-- /GLOBAL-LOADER -->

templates/menu.html
{% load static %}
<div class="sticky">
    <div class="app-sidebar__overlay" data-bs-toggle="sidebar"></div>
    <div class="app-sidebar">
        <div class="side-header">
            <a class="header-brand1" href="{% url 'index' %}">
                <!-- light -->
                <!-- big logo -->
                <img src="{% static 'assets/images/brand/vidoneplus_mainlogo.png' %}" class="header-brand-img desktop-logo" alt="logo">
                <!-- small logo -->
                <img src="{% static 'assets/images/brand/vidoneplus-1.png' %}" class="header-brand-img toggle-logo" alt="logo">

                <!-- dark logo -->
                <!-- big logo -->
                <img src="{% static 'assets/images/brand/vidoneplus_mainlogo.png' %}" class="header-brand-img light-logo1" alt="logo">
                <!-- small logo -->
                <img src="{% static 'assets/images/brand/vidoneplus-1.png' %}" class="header-brand-img light-logo" alt="logo">
            </a>
            <!-- LOGO -->
        </div>
        <div class="main-sidemenu">
            <div class="slide-left disabled" id="slide-left">
                <svg xmlns="http://www.w3.org/2000/svg"
                     fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                    <path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z"/>
                </svg>
            </div>
            <ul class="side-menu">
                <li class="sub-category">
                    <h3>خانه</h3>
                </li>
                <li class="slide">
                    <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'index' %}">
                        <i class="side-menu__icon fe fe-home"></i>
                        <span class="side-menu__label">خانه</span>
                    </a>
                </li>
                {% if request.user.status.active_user %}
                    <li class="sub-category">
                        <h3>سایت</h3>
                    </li>
                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'client:setting' %}">
                            <i class="side-menu__icon fe fe-settings"></i>
                            <span class="side-menu__label">تنظیمات</span>
                        </a>
                    </li>
                    <li class="sub-category">
                        <h3>خدمات دوره‌ای</h3>
                    </li>
                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
                            <i class="side-menu__icon fe fe-clock"></i>
                            <span class="side-menu__label">سرویس‌های دوره‌ای</span>
                            <i class="angle fe fe-chevron-right"></i>
                        </a>
                        <ul class="slide-menu">
                            <li>
                                <a href="{% url 'order:orders' %}" class="slide-item">
                                    <i class="side-menu__icon fe fe-shopping-bag"></i>
                                    سرویس‌ها
                                </a>
                            </li>
                            {% if request.user.is_superuser %}
                                <li>
                                    <a href="{% url 'order:order_create' %}" class="slide-item">
                                        <i class="side-menu__icon bi bi-plus-lg"></i>
                                        ساخت سرویس جدید
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </li>
                {% endif %}
                {% if request.user.is_superuser %}
                    <li class="sub-category">
                        <h3>بخش ادمین</h3>
                    </li>
                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
                            <i class="side-menu__icon fe fe-cpu"></i>
                            <span class="side-menu__label">منوی ادمین</span>
                            <i class="angle fe fe-chevron-right"></i>
                        </a>
                        <ul class="slide-menu">
                            <li>
                                <a href="{% url 'client:users' %}" class="slide-item">
                                    <i class="side-menu__icon fe fe-users"></i>
                                    مدیریت کاربران
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'client:versions' %}" class="slide-item">
                                    <i class="side-menu__icon bi bi-clipboard-data"></i>
                                    ورژن‌ها
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'client:sites' %}" class="slide-item">
                                    <i class="side-menu__icon fa fa-firefox"></i>
                                    سایت ها
                                </a>
                            </li>
                        </ul>
                    </li>
                    <!--li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
                            <i class="side-menu__icon bi bi-clipboard-data"></i>
                            <span class="side-menu__label">ورژن‌ها</span>
                            <i class="angle fe fe-chevron-right"></i>
                        </a>
                        <ul class="slide-menu">
                            <li><a href="alerts.html" class="slide-item"> Alerts</a></li>
                            <li class="sub-slide">
                                <a class="sub-side-menu__item" data-bs-toggle="sub-slide" href="javascript:void(0)">
                                    <span class="sub-side-menu__label">Avatars</span>
                                    <i class="sub-angle fe fe-chevron-right"></i>
                                </a>
                                <ul class="sub-slide-menu">
                                    <li><a href="avatarsquare.html" class="sub-slide-item"> Avatar-Square</a></li>
                                    <li><a href="avatar-round.html" class="sub-slide-item"> Avatar-Rounded</a></li>
                                    <li><a href="avatar-radius.html" class="sub-slide-item"> Avatar-Radius</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li-->
                {% endif %}
            </ul>
            <div class="slide-right" id="slide-right">
                <svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191"
                     width="24" height="24" viewBox="0 0 24 24">
                    <path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z"/>
                </svg>
            </div>
        </div>
    </div>
    <!--/APP-SIDEBAR-->
</div>