client/urls.py
from django.urls import path, include
from .views import *
from .api import *

app_name = 'client'
urlpatterns = [
    path('', dashboard, name='dashboard'),

    path('profile/', profile, name='profile'),
    path('profile/password/', changepassword, name="password"),
    path('user/edit/<int:user_id>/', user_edit, name='user_edit'),

    path('setting/', user_settings, name="setting"),
    path('setting/edit/', user_settings, {'action': 'edit'}, name="setting_edit"),

    path('setting/<str:domain>/<path:path>', static_files, name="static_files"),

    path('login/', login, name='login'),
    path('verify/<str:user_cellphone>/', verify, name='verify'),
    path('logout/', Logout, name="logout"),

    path('status/', status, name="status"),

    path('users/', users, name="users"),
    path('users/<int:user_id>/active', activate_user, name='activeuser'),
    path('users/<int:user_id>/deactive', deactivate_user, name='deactiveuser'),
    path('plus_update_pass/', plus_update_pass, name="plus_update_pass"),

    path('admin/', admin, name="admin"),
    path('admin/<int:id>/', admin, name="admin"),
    path('admin/<int:id>/install/', admininstall, name="admininstall"),
    path('admin/<int:id>/install-sites/', install_sites, name="install-sites"),
    path('admin/<int:id>/remove/', adminremove, name="adminremove"),
    path('admin/<int:id>/siteuser/', check_or_createuser, name="siteuser"),
    path('admin/<str:id>/<str:user>/resetpassword/', resetpassword, name="resetpassword"),

    path('versions/', versions, name='versions'),
    path('versions/delete/<int:image_tag_id>/', version_delete, name='version_delete'),
    path('version/edit/<int:image_tag_id>/', version_edit, name='version_edit'),
    path('version/create/', version_create, name='version_create'),
    path('version/active/<int:id>/', edit_verion, {'action' : 'active'}, name="active_verion"),
    path('version/deactive/<int:id>/', edit_verion, {'action' : 'deactive'}, name="deactive_verion"),

    path('sites/', sites, name="sites"),

    # api
    path('api/select/theme/', api_select_theme, name='api_select_theme'),
    path('api/get/domain/config/<str:domain>/', api_get_domain_config, name='api_get_domain_donfig'),
    path('api/available/versions/', api_get_available_force_version, name='api_available_versions'),



    # should be moved
    path('timing/<int:user_id>/', timing, name='timing'),


    path('user/orders/', include('client.views.user_order.urls'), name='user_order'),
]

order/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('', orders, name='orders'),
    path('order/create/', order_create, name='order_create'),
    path('order/edit/<int:order_id>/', order_edit, name='order_edit'),
    path('order/delete/<int:order_id>/', order_delete, name='order_delete'),
    path('order/detail/<int:order_id>/', order_detail, name='order_detail'),
    path('order/buy/<int:order_id>/', order_buy, name='order_buy'),
    path('order/buy/<int:order_id>/<int:setting_id>/', order_buy, name='order_buy'),

    path('static/files/<int:order_id>/', static_files, name='static_files')
]

vidoneplus/urls.py
from django.contrib import admin
from django.urls import path, include
from vidoneplus.views import *

urlpatterns = [
    path('', index, name="index"),
    path('validate_course/', validate_course),
    path('admin/', admin.site.urls),
    path('accounts/', include('client.urls')),
    path('course/', include('course.urls')),
    path('order/', include('order.urls')),
    path('page_not_found/', page_not_found, name='page_not_found'),
    path('page_not_found/<str:text>/', page_not_found, name='page_not_found'),
    path('page_not_found/<str:text>/<str:previous_url>/', page_not_found, name='page_not_found'),
]

client/models.py
import datetime
import jdatetime
from unidecode import unidecode
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import login


def user_image(instance, filename):
    return "%s/%s/%s" % ('setting', instance.owner.id, filename)


class User(AbstractUser):
    cellphone = models.CharField(max_length=15, unique=True)
    organization_name = models.CharField(max_length=15)
    educational_interface_name = models.CharField(max_length=200)
    description = models.TextField()
    dateofestablishment = models.DateField(null=True)
    extra = models.JSONField(default=dict)

    @staticmethod
    def get_user(username):
        user = User.objects.filter(Q(cellphone=username) | Q(email=username) | Q(username=username)).first()
        if user:
            return user
        return User()

    def save(self, *args, **kwargs):
        self.cellphone = unidecode(self.cellphone)
        self.username = self.cellphone
        super(User, self).save()

    def sendsms(self):
        if not self.cellphone:
            return False
        code = self.create_verificationcode()
        try:
            from library.smsir import Smsir
            sms = Smsir()
            sms.sendwithtemplate({'verificationCode': code}, self.cellphone, 55907)
        except (Exception, Exception):
            print('احتمالا اعتبار سامانه‌ی پیامکی تمام شده است!')
        print(code)

    def login(self, request):
        if self.is_active:
            login(request, self)
            return True
        return False

    def check_code(self, request, code):
        status = False
        if self.get_verificationcode() == code:
            status = self.login(request)
            VerificationCode.objects.filter(name=self.username).delete()
        return status

    def create_verificationcode(self):
        self.username = unidecode(self.username)
        VerificationCode.objects.filter(name=self.username).delete()
        vc = VerificationCode(name=self.username)
        vc.save()
        return str(vc.code)

    def get_verificationcode(self):
        VerificationCode.objects.filter(name=self.username, trying__gt=5).delete()
        try:
            vc = VerificationCode.objects.get(name=self.username)
            vc.trying += 1
            vc.save()
            return str(vc.code)
        except (VerificationCode.DoesNotExist, Exception):
            pass
        return None

    @staticmethod
    def check_phone_validate(self):
        prev_numbers = [
            '+93', '+355', '+213', '+1684', '+376', '+244', '+1264', '+1268', '+54', '+374', '+297',
            '+61', '+43', '+994', '+1242', '+973', '+880', '+1246', '+375', '+32', '+501', '+229',
            '+1441', '+975', '+591', '+599', '+387', '+267', '+55', '+1284', '+673', '+359', '+226',
            '+257', '+855', '+237', '+1', '+238', '+1345', '+236', '+235', '+56', '+86', '+57', '+269',
            '+243', '+242', '+682', '+506', '+225', '+385', '+53', '+599', '+357', '+420', '+45', '+246',
            '+253', '+1767', '+1809', '+1829', '+1849', '+593', '+20', '+503', '+240', '+291', '+372',
            '+268', '+251', '+500', '+298', '+679', '+358', '+33', '+594', '+689', '+241', '+220', '+995',
            '+49', '+233', '+350', '+30', '+299', '+1473', '+590', '+1671', '+502', '+224', '+245',
            '+592', '+509', '+504', '+852', '+36', '+354', '+91', '+62', '+98', '+964', '+353', '+972',
            '+39', '+1876', '+81', '+962', '+7', '+254', '+686', '+383', '+965', '+996', '+856', '+371',
            '+961', '+266', '+231', '+218', '+423', '+370', '+352', '+853', '+261', '+265', '+60', '+960',
            '+223', '+356', '+692', '+596', '+222', '+230', '+52', '+691', '+373', '+377', '+976', '+382',
            '+1664', '+212', '+258', '+95', '+264', '+674', '+977', '+31', '+687', '+64', '+505', '+227',
            '+234', '+683', '+672', '+850', '+389', '+1670', '+47', '+968', '+92', '+680', '+970', '+507',
            '+675', '+595', '+51', '+63', '+48', '+351', '+1787', '+1939', '+974', '+262', '+40', '+7',
            '+250', '+247', '+290', '+1869', '+1758', '+508', '+1784', '+685', '+378', '+239', '+966',
            '+221', '+381', '+248', '+232', '+65', '+1721', '+421', '+386', '+677', '+252', '+27', '+82',
            '+211', '+34', '+94', '+249', '+597', '+46', '+41', '+963', '+886', '+992', '+255', '+66',
            '+670', '+228', '+690', '+676', '+1868', '+216', '+90', '+993', '+1649', '+688', '+256',
            '+380', '+971', '+44', '+598', '+1340', '+1', '+998', '+678', '+58', '+84', '+681', '+967',
            '+260', '+263'
        ]
        if self.cellphone:
            prev = self.cellphone[:-10]
            if prev in prev_numbers:
                return True
        return False

    def get_status(self):
        return self.status

    @staticmethod
    def not_empty(request, request_method, *args):
        if request_method == 'POST':
            for input_name in args:
                if not request.POST.get(input_name):
                    return False
        else:
            for input_name in args:
                if not request.GET.get(input_name):
                    return False
        return True

    @staticmethod
    def str_to_date(string_date):
        d = datetime.datetime.strptime(string_date, '%Y/%m/%d').date()
        return jdatetime.date(d.year, d.month, d.day).togregorian()


class VerificationCode(models.Model):
    name = models.CharField(max_length=100, primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    code = models.IntegerField()
    trying = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        import random
        if not self.code:
            self.code = random.randint(1000, 9999)
        super(VerificationCode, self).save()


class Imagetag(models.Model):
    status = models.BooleanField(default=True)
    forceupdate = models.BooleanField(default=False)
    pwa_version = models.CharField(max_length=20)
    pwa_description = models.CharField(max_length=200)
    admin_version = models.CharField(max_length=20)
    admin_description = models.CharField(max_length=200)
    site_version = models.CharField(max_length=20)
    site_description = models.CharField(max_length=200)
    android_version = models.CharField(max_length=20)
    android_description = models.CharField(max_length=200)
    ios_version = models.CharField(max_length=20)
    ios_description = models.CharField(max_length=200)


class Setting(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    org_color = models.CharField(max_length=50)
    sub_color = models.CharField(max_length=50)
    app_name = models.CharField(max_length=250)
    domain = models.CharField(max_length=50)
    kuberid = models.CharField(max_length=250, null=True, blank=True)
    site_name = models.CharField(max_length=250, null=True, blank=True)
    admin_name = models.CharField(max_length=250, null=True, blank=True)
    pwa_name = models.CharField(max_length=250, null=True, blank=True)
    fullname = models.CharField(max_length=250, null=True, blank=True)
    contact_phone = models.CharField(max_length=250)
    download_link = models.CharField(max_length=500)
    company_logo = models.ImageField(upload_to=user_image)
    splashscreen = models.ImageField(upload_to=user_image)
    image_tag = models.ForeignKey(Imagetag, on_delete=models.CASCADE, null=True)
    instagram = models.CharField(max_length=50, null=True, blank=True)
    aparat = models.CharField(max_length=50, null=True, blank=True)
    facebook = models.CharField(max_length=50, null=True, blank=True)
    twitter = models.CharField(max_length=70, null=True, blank=True)
    youtube = models.CharField(max_length=70, null=True, blank=True)
    favicon = models.ImageField(upload_to=user_image)
    short_title = models.CharField(max_length=50, null=True, blank=True)
    slogan = models.CharField(max_length=50, null=True, blank=True)
    zarinpal = models.CharField(max_length=50, null=True, blank=True)
    smsir_key = models.CharField(max_length=50, null=True, blank=True)

    def get_splashscreen(self):
        return self.splashscreen.path.split('/')[-1]

    def get_company_logo(self):
        return self.company_logo.path.split('/')[-1]

    def get_favicon(self):
        return self.favicon.path.split('/')[-1]


# class CourseVitrin(models.Model):
#     title = models.CharField(max_length=200)
#     description = models.TextField()
#     price = models.BigIntegerField()
#     price_with_discount = models.BigIntegerField(default=0)
#     teacher = models.CharField(max_length=200)
#     lesson_count = models.IntegerField(default=0)
#
#     def save(self, *args, **kwargs):
#         super(CourseVitrin, self).save()
#
#     def buyed(self, user):
#         try:
#             CourseUser.objects.get(course=self, user=user)
#             return True
#         except:
#             return False


class Status(models.Model):
    active_user = models.BooleanField(default=False)
    site_created = models.BooleanField(default=False)
    duration = models.IntegerField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)


# class CourseUser(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     course = models.ForeignKey(Course, on_delete=models.CASCADE)
#     status = models.BooleanField(default=False)

class PasswordGenerator(models.Model):
    setting = models.ForeignKey(Setting, on_delete=models.CASCADE)
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)

order/views/imports.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from order.models import *
from client.models import User, Setting
from bill.models import Bill
from library.decorators import is_superuser, id_is_real
import os, mimetypes, datetime, math

order/views/order_buy.py
from .imports import *


@login_required
@id_is_real(Order)
def order_buy(request, order_id, setting_id=None):
    context = {}
    user = User.objects.get(id=request.user.id)
    order = Order.objects.get(id=order_id)
    if request.method == 'POST':
        user_setting = Setting.objects.get(id=setting_id)
        if user_setting.orderitem_set.exists():  # if user's site has order
            order_item = user.setting_set.get(id=setting_id).orderitem_set.last()
            now = datetime.datetime.now()
            if now.timestamp() > order_item.ended_at.timestamp() and (not order_item.status):  # if user's site time end
                order = OrderItem.objects.create(
                    order=order,
                    setting=user_setting
                )
                order.save()
                Bill.objects.create(order_item=order).save()
            else:
                request.session['active_order'] = True
                return redirect(reverse('order:order_buy', kwargs={'order_id': order_id, 'setting_id': setting_id}))
        else:
            order = OrderItem.objects.create(
                order=order,
                setting=user_setting
            )
            order.save()
            Bill.objects.create(order_item=order).save()
        return redirect(reverse('client:profile'))
    context['order'] = order
    if request.session.get('active_order'):
        context['active_order'] = True
        del request.session['active_order']
    return render(request, f'{__name__.replace(".", "/")}.html', context)

order/views/order_create.py
from .imports import *


@login_required
@is_superuser
def order_create(request):
    context = {}
    if request.method == 'POST':
        order = Order()
        order.title = request.POST.get('title')
        order.description = request.POST.get('description')
        order.price = request.POST.get('price')
        if not request.POST.get('period').isnumeric():
            return redirect(reverse('order:order_create'))
        order.period = int(request.POST.get('period'))
        if request.FILES.get('image'):
            order.image = request.FILES.get('image')
        order.save()
        request.session['save'] = True
        return redirect(reverse('order:order_edit', kwargs={'order_id': order.id}))
    return render(request, f'{__name__.replace(".", "/")}.html', context)

order/views/order_delete.py
from .imports import *


@login_required
@is_superuser
def order_delete(request, order_id):
    order = Order.objects.get(id=order_id)
    order.status = False
    order.save()
    return redirect(reverse('order:orders'))

order/views/order_detail.py
from .imports import *


@login_required
def order_detail(request, order_id):
    context = {}
    print(order_id)
    context['order'] = Order.objects.get(id=order_id)
    return render(request, f'{__name__.replace(".", "/")}.html', context)

order/views/order_edit.py
from .imports import *


@login_required
def order_edit(request, order_id):
    context = {}
    order = Order.objects.get(id=order_id)
    if request.method == 'POST':
        order.title = request.POST.get('title')
        order.description = request.POST.get('description')
        order.price = request.POST.get('price')
        if not request.POST.get('period').isnumeric():
            return redirect(reverse('order:order_create'))
        order.period = int(request.POST.get('period'))
        if request.FILES.get('image'):
            order.image = request.FILES.get('image')
        order.save()
        request.session['update'] = True
        return redirect(reverse('order:order_edit', kwargs={'order_id': order_id}))
    context['order'] = order
    if request.session.get('save'):
        context['save'] = True
        del request.session['save']
    if request.session.get('update'):
        context['update'] = True
        del request.session['update']
    return render(request, f'{__name__.replace(".", "/")}.html', context)

templates/order/views/order_buy.html
{% extends 'base.html' %}
{% load static %}
{% load client %}
{% block title %}خرید سرویس{% endblock %}
{% load jformat %}
{% block css %}
    <style>
        .hero-picture {
            background-image: url('{% url 'order:static_files' order.id %}');
            background-repeat: no-repeat;
            background-size: cover;
            border-radius: 6px;
            transition: all 0.4s;
        }

        .hero-container:hover .hero-picture {
            filter: blur(3px);
        }

        .hero-container:hover .hero-text {
            filter: blur(0);
        }

        .hero-text {
            transition: all 0.4s;
            filter: blur(3px);
            z-index: 2;
            top: 2%;
        }
    </style>
{% endblock %}
{% block js %}

    <!-- FILE UPLOADES JS -->
    <script src="{% static 'assets/plugins/fileuploads/js/fileupload.js' %}"></script>
    <script src="{% static 'assets/plugins/fileuploads/js/file-upload.js' %}"></script>

    <!-- INTERNAL File-Uploads Js-->
    <script src="{% static 'assets/plugins/fancyuploder/jquery.ui.widget.js' %}"></script>
    <script src="{% static 'assets/plugins/fancyuploder/jquery.fileupload.js' %}"></script>
    <script src="{% static 'assets/plugins/fancyuploder/jquery.iframe-transport.js' %}"></script>
    <script src="{% static 'assets/plugins/fancyuploder/jquery.fancy-fileupload.js' %}"></script>
    <script src="{% static 'assets/plugins/fancyuploder/fancy-uploader.js' %}"></script>


    <script>
        {% if save %}
            $(window).on('load', () => {
                setTimeout(function () {
                    Toastify({
                        text: 'سرویس ساخته شد!',
                        duration: 1500,
                        newWindow: true,
                        close: true,
                        gravity: 'top', // `top` or `bottom`
                        position: 'center', // `left`, `center` or `right`
                        stopOnFocus: true, // Prevents dismissing of toast on hover
                        style: {
                            background: 'rgb(108,95,252)',
                        },
                        onClick: function () {
                        } // Callback after click
                    }).showToast();
                }, 350);
            });
        {% endif %}
        {% if update %}
            $(window).on('load', () => {
                setTimeout(function () {
                    Toastify({
                        text: 'تغییرات با موفقیت ذخیره شدند!',
                        duration: 1500,
                        newWindow: true,
                        close: true,
                        gravity: 'top', // `top` or `bottom`
                        position: 'center', // `left`, `center` or `right`
                        stopOnFocus: true, // Prevents dismissing of toast on hover
                        style: {
                            background: 'rgb(108,95,252)',
                        },
                        onClick: function () {
                        } // Callback after click
                    }).showToast();
                }, 350);
            });
        {% endif %}
        {% if active_order %}
            setTimeout(function () {
                Toastify({
                    text: 'دوره‌ی سرویس شما هنوز تمام نشده است!',
                    duration: 4000,
                    newWindow: true,
                    close: true,
                    gravity: 'top', // `top` or `bottom`
                    position: 'center', // `left`, `center` or `right`
                    stopOnFocus: true, // Prevents dismissing of toast on hover
                    style: {
                        background: 'rgb(108,95,252)',
                    },
                }).showToast();
            }, 350);
        {% endif %}
    </script>
{% endblock %}
{% block body %}

    <!-- GLOBAL-LOADER -->
    {% comment %}{% include 'loader.html' %}{% endcomment %}
    <!-- /GLOBAL-LOADER -->

    <!-- app-Header -->
    {% include 'header.html' %}
    <!-- /app-Header -->

    <!--APP-SIDEBAR-->
    {% include 'menu.html' %}

    <!--app-content open-->
    <div class="main-content app-content mt-0">
        <div class="side-app">
            <!-- CONTAINER -->
            <div class="main-container container-fluid">
                <!-- PAGE-HEADER OPTIONAL TO WRITE SOME DATA ABOUT request.user -->
                <div class="page-header">
                    <div class="d-flex">
                        <h1 class="page-title px-2">
                            {% if request.META.HTTP_REFERER %}
                                <a href="{{ request.META.HTTP_REFERER }}">
                                    <i class="fa fa-arrow-right"></i>
                                    برگشت
                                </a>
                            {% endif %}
                        </h1>
                        <h1 class="page-title px-2">خرید سرویس</h1>
                    </div>
                    <div>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{% url 'order:orders' %}">سرویس‌ها</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">خرید سرویس</li>
                        </ol>
                    </div>
                </div>
                <!-- PAGE-HEADER END -->

                <!-- write your code here -->
                <div class="row">
                    <div class="col-md-12 col-xl-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                    خرید سرویس جدید
                                </h3>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 my-3 position-relative hero-container"
                                         style="height:{% if order.image.height %}{{ order.image.height }}px{% else %}400px{% endif %}">
                                        <div class="d-flex justify-content-center">
                                            <div class="position-absolute hero-text">
                                                <p class="font-bold h2">مشخصات سرویس</p>
                                            </div>
                                        </div>
                                        <div class="hero-picture h-100"></div>
                                    </div>
                                    <div class="col-12 my-3">
                                        <div class="row">
                                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                                                <div class="d-flex justify-content-start">
                                                    <p class="font-bold h4 px-3">نام سرویس</p>
                                                    <p class="px-3 h5">{{ order.title }}</p>
                                                </div>
                                            </div>
                                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                                                <div class="d-flex justify-content-start">
                                                    <p class="font-bold h4 px-3">نام قیمت</p>
                                                    <p class="px-3 h5">{{ order.price|persian_numbers }} هزارتومان</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-12 px-5">
                                                <p class="font-thin lead">{{ order.description|linebreaksbr }}</p>
                                            </div>
                                        </div>
                                        <hr/>
                                        <div class="row">
                                            <div class="col-12 d-flex justify-content-center">
                                                <h3><strong class="font-bold">سایت خود را انتخاب کنید</strong></h3>
                                            </div>
                                        </div>
                                        <div class="row">
                                            {% for s in user.setting_set.all %}
                                                <div class="col-sm-12 col-md-12 col-lg-6 col-xl-3">
                                                    <div class="thumbnail">
                                                        <a href="{% url 'client:setting' %}">
                                                            <img src="{% url 'client:static_files' s.domain s.get_company_logo %}" alt="thumb1" class="thumbimg">
                                                        </a>
                                                        <div class="caption">
                                                            <h4><strong>{{ s.domain }}</strong></h4>
                                                            <p>{{ s.app_name }}</p>
                                                            <form method="post" action="{% url 'order:order_buy' order.id s.id %}">
                                                                {% csrf_token %}
                                                                <button type="submit" class="btn btn-primary w-100">خرید</button>
                                                            </form>
{#                                                                <label class="custom-control custom-radio custom-radio-md">#}
{#                                                                    <input type="radio" class="custom-control-input" name="setting" value="{{ s.id }}">#}
{#                                                                    <h4><span class="custom-control-label">انتخاب</span></h4>#}
{#                                                                </label>#}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /write your code here -->

            </div>
            <!-- CONTAINER END -->
        </div>
    </div>
    <!--app-content close-->


    <!-- Sidebar-right -->
    {% comment %}
    {% include 'side_bar.html' %}
    {% endcomment %}
    <!--/Sidebar-right-->

    <!-- Country-selector modal-->
    {% comment %}
    {% include 'country_selector.html' %}
    {% endcomment %}
    <!-- Country-selector modal-->

    <!-- FOOTER -->
    {% include 'footer.html' %}
    <!-- FOOTER END -->

    <!-- BACK-TO-TOP -->
    <a href="#top" id="back-to-top"><i class="fa fa-angle-up"></i></a>
{% endblock %}